### ISSUE TITLE
images

### ISSUE THREAD

**Issue by cldn1024** [KMU309/Origin-Chain#1]
![maxresdefault](https://user-images.githubusercontent.com/35910566/51069720-0490dd00-1678-11e9-9ad9-903d9535dc8f.jpg)

**Comment by cldn1024** [comment]
![maxresdefault 1](https://user-images.githubusercontent.com/35910566/51069729-16728000-1678-11e9-8943-18376d722a1d.jpg)

**Comment by woosung-jo** [comment]
원산지 증명서

수입물품의 원산지증명서는 크게 두 가지 용도로 활용된다.

첫 번째는 관세양허대상이 아닌 수출물품에 대하여 
해외 바이어의 자국 내 원산지 표시 문제 및 불공정무역행위 방지 등의 목적을 이유로 
발급되는 비특혜 원산지증명서가 있다. 

두 번째는 자유무역협정(FTA)에 의한 관세양허 수출물품의 
원산지를 증명하기 위한 목적으로 발급되는 특혜 원산지증명서이다.

**Comment by woosung-jo** [comment]
관세청이 적발한 지난해 수입,수출 원산지 표시위반은 모두 705건으로 약 8665억 원 규모이다.
전년 683건 3828억 원에 비해 각각 3.2%, 126.3% 늘어난 수치이다.

// http://bizn.donga.com/3/all/20151119/74866913/3

원산지를 허위 표시하거나 눈에 띄지 않는 곳에 표시하는 수법 등 `원산지표시 면제제도`를 악용하는 사례가 급증하고 있다.
관세청은 그 동안 원산지표시위반 사례가 잦거나 원산지표시 면제제도를 악용할 것으로 예상되는 
품목군을 선별·분석, 자동차부품 등 10여가지 품목에 대해 지난 6월부터 50여일간 원산지표시 
실태조사와 함께 집중단속을 시행했다고 5일 밝혔다.


- 이유
원산지표시 면제제도`란 대외무역관리규정에 따라 제조공정에 투입되는 
부품·원재료 등 정해진 품목에 대해 원산지표시의무를 면제해주는 제도다.
그 결과 자동차 안전유리, 가방, 주방용품, 물놀이용품 등의 원산지표시
 위반(78개 업체, 97억원 상당)을 적발하고 시정조치·과징금을 부과했다.

// https://news.joins.com/article/6134257

**Comment by cldn1024** [comment]
최근 3년간 원산지 표시 위반으로 관세청이 시정조치한 수입 규모가 두 배로 불어나 `무역 강국`을 표방하는 우리나라가 수출 성적뿐 아니라 수입 관리도 강화할 필요가 있다는 주장이 제기됐다. 

7일 매일경제신문이 이종배 자유한국당 의원에게 입수한 관세청 `원산지 표시 손상·변형에 따른 시정조치 현황` 자료에 따르면 원산지 표시 손상·변형으로 단속된 수입물품 규모는 2015년 4503억원에서 꾸준히 늘어 작년에는 8901억원으로 두 배가량 증가했다. 

2015년부터 올해 7월까지 수입된 원산지표시대상물품 중 원산지 표시를 손상하거나 불법으로 바꾸는 바람에 관세청으로부터 시정조치를 받은 경우는 100만건(적발액 총 2조2163억원 상당)에 달했다. 

연간 시정조치 내역 통계를 보면 2015~2017년 총 적발액이 큰 품목은 철강제품(6636억9700만원), 석재·유리(3462억1800만원)등이었고, 전자제품과 농수산물, 차량·자전거 등 다양한 품목들이 포함됐다.

**Comment by cldn1024** [comment]
![image](https://user-images.githubusercontent.com/35910566/51074564-f2d52700-16c3-11e9-83eb-a2688ba576a5.jpg)

**Comment by cldn1024** [comment]
![image](https://user-images.githubusercontent.com/35910566/51079471-ed4eff80-170a-11e9-8e32-987c6f1865e8.jpg)
